### ISSUE TITLE
USILS.ViewingCupola does not have a hatch

### ISSUE THREAD

**Issue by s7jones** [BobPalmer/USI-LS#139]
But because it is a command module, it is used in stock kerbal rescue missions, but they cannot EVA out of the cupola once you come close.

**Comment by s7jones** [comment]
I wonder if this part might be from MKS instead?

And that some additional fixes in the vein of this pull request? https://github.com/BobPalmer/MKS/pull/555

**Comment by Ferigad** [comment]
Hehehe, i encountered the same issue. Getting closer, thinking yeah it´s just a search and rescue, no big deal. Want to get the kerbal out and get... that module has no hatch! .... Whaaaaaaaat? Thats really an issue. Not directly a bug but deffinitly something that should be corrected.  As far as i know that part is from Life Support. I just got it when i was using the Life Support Mod instead of TAC Life support.

**Comment by jd284** [comment]
As a side note, install [KSP Rescue Pod Validator](http://forum.kerbalspaceprogram.com/index.php?/topic/141560-12-ksp-rescue-pod-validator-no-more-kerbals-spawning-in-inflatable-modules/) to prevent this for future contracts.

**Comment by BobPalmer** [comment]
Known issue, not all habitable parts have hatches.
