### ISSUE TITLE
Got a rescue contract for a viewing cupola

### ISSUE THREAD

**Issue by lawnsea** [BobPalmer/USI-LS#190]
I accepted a rescue contract to save Billy-Bobbles from low Kerban orbit. Once I got up there, he turned out to be in a viewing cupola, which doesn't have an EVA capability, or (as far as I can tell) docking ports. I haven't broken the bad news to Billy yet.

**Comment by Saelack** [comment]
The issue here isn't this mod - it's that you don't have enough mods.  You
need
http://forum.kerbalspaceprogram.com/index.php?/topic/141560-122-ksp-rescue-pod-validator-no-more-kerbals-spawning-in-inflatable-modules/
this mod as well.  Well, actually, the issue (not problem per se) is that
by default the contract system will assign a rescue contract to any part
that can take crew - the Rescue Pod Validator mod will make sure that the
part in question actually has a _hatch_ as well, which saves you from that
embarrassment.

**Comment by lawnsea** [comment]
Thanks, @Saelack! I will install that mod to work around the problem. In the meanwhile, I'm going to leave this bug open for @BobPalmer to decide if a fix is warranted in this mod.

**Comment by jd284** [comment]
You should close it. There's nothing a mod can do about its parts being selected for rescue contracts.
