### ISSUE TITLE
Recyclers no longer shared for disconnected base

### ISSUE THREAD

**Issue by jd284** [BobPalmer/USI-LS#209]
Since a few days ago, recyclers only apply vessel-wide, before that they also applied to other vessels within a disconnected base. Now all other vessels show the full unrecycled supply consumption in the USI-LS info window.

There was no mention of a change like this in the changelog, so reporting this as a bug.

Habitation is still shared with nearby vessels though.

**Comment by Gnurfos** [comment]
This has been introduced by some optimization done here: https://github.com/BobPalmer/USI-LS/commit/7a9ca08150b2f4798348a8d66333db77eb467a4f#diff-8fe9cb7376074c990c68fd0564c5d535
(By the way I'm not sure switching to indexed iterations is that fruitful. If these sections are called too often, some kind of caching mecanism would probably be more effective).

Reverting to previous behaviour should be simply a matter of reintroducing a:
` v.FindPartModulesImplementing<ModuleLifeSupportRecycler>()`
to iterate over recyclers of other vessels, instead of re-looping on current vessel ones.

But I think the whole algorithm for sharing recyclers is flawed as it is:

- summing the percents for different parts (regardless of the number of vessels considered) is not meaningful and will tend to make the total big, so that in the end, the "cap" is always selected unscaled (the best recycler present)
- there is something strange with CrewCapacity: it is used to scale a recycler's effect when it applies to a vessel's Kerbals, but nothing marks that it is "used up" in the process, so the recycler could potentially be reused for other vessels. I suppose the summing tries to mitigate that, but don't think it works

**Comment by jd284** [comment]
Fixed in 0.5.20
