### ISSUE TITLE
USI-LS causes Taurus HCV LES fire on launch (and promptly consume all monopropellant)

### ISSUE THREAD

**Issue by aleander** [BobPalmer/USI-LS#7]
Tested with Taurus HCV 1.5.01, USI-LS 1.2.0, BD Animation 6.0 (this is an upgrade from the one bundled with Taurus HCV, but I remember the issue there), MM 2.6.3. Otherwise it's vanilla. Here's a gist of the log: https://gist.github.com/aleander/aa147779f64926cac190.

**Comment by shadowmage45** [comment]
I have the same/related error with a custom command-pod part that I am working on.  It includes a decoupler and engine (both stock modules);  on inclusion of the LifeSupport module (whether manually or through the default MM patch), it will fire the decoupler and start the engine the moment the vessel is focused or launched, regardless of staging order.  If I delete the default LifeSupport MM patch, or otherwise exclude the pod from the patch, everything functions as normal.

Will update with more info and logs as I investigate further.

**Comment by aleander** [comment]
Due to this being noticed in the Taurus thread again, I just checked by replacing USI-LS with this file: https://gist.github.com/aleander/90aefd7c62cbb8d6e67f

This triggered the bug as well (I did it based on ModuleLifeSupport inheriting from BaseConverter, which I lazily assumed comes from Stock and is a base for other converters). So, it seems it's a stock bug?

**Comment by BobPalmer** [comment]
This is a function of how stock converters work.  So the Taurus HCV is not compatible with this mod.

**Comment by shadowmage45** [comment]
What can be done to resolve this problem on the part of the part authors?  I have many complex parts that exhibit issues when the LS mod is installed.  Some could possibly be redesigned.  However some cannot;  Is there -always- going to be a problem on parts that have engines/decouplers?  (Most of my custom welded parts combine a command pod with fuel tanks/rcs/engines/decouplers, and seemed to suffer from this issue)

Is there a way to rework the LS to -not- use the (apparently very buggy) stock resource converter code?

Would submitting a bug report to Squad to fix the issue in stock help?

A better question is... why in @!#%^ is the stock converter module triggering staging actions?

Anything that -I- can do to help get this problem actually resolved?

I have been holding off on adding the USI mods to my 1.02 game until this can get resolved (as I rely on a lot of welded and custom designed parts for low-part-count vessels), but am really starting to miss my stations and bases.... (and what is the point without life support requirements?)

**Comment by BobPalmer** [comment]
The answer is to not put people inside of engines.  Leaving this closed, and courtesy is important.

**Comment by shadowmage45** [comment]
I was not meaning to sound disrespectful or discourteous;  I'm sorry if it came off sounding that way.  I was merely trying to offer my time and help to get this problem resolved.  As a long term mod developer (Minecraft...), I fully appreciate the time and effort that you put in, and do not mean to undermine that in any manner.

BTW -- its not just engines;  A pod with a built-in parachute will suffer the same stage-on-launch problem.  In testing, it is anything with a staging action is incompatible with the source BaseConverter...

I have tracked down the issue in the stock source code, and am willing to -try- and develop a fix if you are open to pull requests on this issue.

**Comment by BobPalmer** [comment]
Oh, I wrote the stock source code for that module ;)  Always open to pull requests tho (just can't change stock obviously).

**Comment by shadowmage45** [comment]
The issue seems to be that BaseConverter and ModuleAnimationGroup (in the ISRU case) call base.part.force_activate();  in their OnStart() methods -- which calls OnActive() for every module on the part, activating whatever staging action it may have.

I suppose I should ask if there was a specific purpose behind that call in those classes (before I try and make a patch to work around it)?  It looks to me that the Part.force_activate() method mostly just activates two (statically named?) FX groups before calling OnActive() on all the modules.

For the life-support case (not needing ModuleAnimationGroup), I think the BaseConverter.OnStart() code would be fairly easy to work around by removing the base.OnStart() call in your overridden method, manually activating the FX groups (if they are even needed in the case of life-support?, would have to find what their names are), and reimplementing the debugging label and other gui label setup that would be skipped from the base call.

If you can't think of any reason(s) why this would be a terrible idea, I'll work on getting a repo and PR setup.

Thanks for your time (and patience) :)

**Comment by shadowmage45** [comment]
I have a fix for this problem developed and in extended testing.  So far all is going well. 

It involved re-implementing the BaseConverter class, trimmed down to only what was necessary for the life support (e.g. removed all heat, specialist, and efficiency code).  There was too much code dealing with private members and methods to cleanly override everything in the ModuleLifeSupport class alone (I found a few more references to part.force_activate() that would have been ugly to work around).

Depending upon view, this could be seen as either a huge hack-around, or a great simplification and streamlining.  Coming from Minecraft modding, this was the de-facto standard for dealing with incompatibilities with stock code and private methods/etc (just re-implement it if you can't override it cleanly).

Changed file
https://github.com/shadowmage45/USI-LS/blob/master/Source/LifeSupport/ModuleLifeSupport.cs

New Converter:
https://github.com/shadowmage45/USI-LS/blob/master/Source/LifeSupport/LifeSupportConverter.cs
(stock converter, trimmed down to only what is needed for LS; -should- maintain backwards compatibility with existing installs, but untested yet)


If you are not opposed to going this route, please let me know and I will open a proper PR.

Thanks again, and sorry to keep bugging you.
