### ISSUE TITLE
Apparent diminishing returns with multiple recyclers

### ISSUE THREAD

**Issue by LouisB3** [BobPalmer/USI-LS#74]
Recyclers appear to underperform in certain circumstances. Example: three pioneer modules (nominal total capacity is 75% recycling for up to 5 * 3 = 15 crew) are supporting an akademy with 12 scientists. With no recycling, supply consumption is 16.2 * 12 = 194.4 per day; with pioneer recycling turned on, expected supply consumption is 194.4 * (1 - .75) = 48.6 per day; actual observed value is 63.2 per day. [Forum report here with screenshot](http://forum.kerbalspaceprogram.com/index.php?/topic/105202-105-usi-life-support-036-bug-fix-update/&page=70#comment-2403193).

**Comment by fat-lobyte** [comment]
Your screenshot is from a disconnected base, and the disconnected mechanics work slightly differently. Could you try to reproduce your issue in one single vessel?

**Comment by LouisB3** [comment]
Sure thing. Here's a quick runway test with the same readouts:

![screen shot 2016-02-29 at 10 24 47 pm](https://cloud.githubusercontent.com/assets/9939641/13416801/4b870c40-df33-11e5-97be-644b25770086.png)

**Comment by jofwu** [comment]
I just went through that portion of code and see why 63.2 is coming up. And I don't think L239 is the issue... I'm confused by what's going on exactly. That is to say, I'm not sure what the code is trying to accomplish with the Crew Capacities.

The relevant portion starts on L199 (https://github.com/BobPalmer/USI-LS/blob/DEVELOP/Source/USILifeSupport/LifeSupportManager.cs#L199). First it searches through the active vessel for activated recycler parts. Then it does the same thing for other vessels within range. I'll go through explaining what I see with LouisB3's numbers in brackets.

**recyclerCap** is the highest recycler rate that it encounters from a single part. [So for LouisB3 that would be 0.75.] It also grabs the number of Kerbals in the colony (**crewCount**) [12 total]. On L215 (and again, for other vessels, on L232) it compares this to the Crew Capacity (**r.CrewCapacity**) *of each individual recylcer part* [5 each]. So for the first recycler it says, "Do you have more Kerbals than this single part can support?" If so, reduce the part's recycle rate (**recPercent**) by that ratio [0.75 * 5/12 = 0.3125]. The decrease on Supply usage is one minus this number, so that's what **recyclerVal** is [1 - 0.3125 = 0.6875]. The weird thing is that it then goes to your next recycler part and reduces **recyclerVal** *again*. It does this for each part in the colony [0.6875 * 0.6875 * 0.6875 = 0.325].

In the end, on the line you pointed out, we choose the maximum of either **recyclerVal** [0.325] or the rate produced by the the best recycler (1 - **recyclerCap**) [1 - 0.75 = 0.25]. So the game is choosing 0.325. When you take the 16.2 Supplies/day rate times 12 Kerbals at this recycle rate you get: 16.2 * 12 * 0.325 = 63.2. Keep in mind that, in this final step, *lower is better*. It appears that this line of code is supposed to be making sure your rate is worsened if you have more crew than you can support.

Now, if you only had one part then this reduction makes sense to me. We can't support 12 Kerbals with this part meant for 5 kerbals, so the usefulness is reduced proportionately. But that's not really what's going on. We don't have 3 parts that are all over capacity by the same amount. _I don't feel like the math is working out the way it was intended to._

I don't know what RoverDude is going for, so I don't know if I can really say for sure what should be done to fix things. It seems like the **recyclerCap** is intended to make sure that you don't get a reduction beyond what the recycler is capable of. In other words, if you have 12 Kerbals and these 75% recyclers are able to support 15 Kerbals then you DON'T get a reduction higher than 75% because you're running under capacity. But I DO think that every Kerbal should be getting a reduction if you're under (or at) capacity. In this case they should all be getting a 75% reduction.

**Comment by BobPalmer** [comment]
Corrected in the next release.
