### ISSUE TITLE
Show life support values in the vessel editor part menu

### ISSUE THREAD

**Issue by LouisB3** [BobPalmer/USI-LS#80]
Currently there's no way to see the following in-game:

- which parts have habitat space, and how much
- which parts have habitat multipliers, and how much
- recycler efficiency or capacity

So to make use of the life support mechanics, new users must resort to:

- adding and removing parts at random while watching the life support window
- consulting external documentation
- or peeking at config files

It would be great to be able to refer to this info in the VAB part menu - example:
 
![screenshot3](https://cloud.githubusercontent.com/assets/9939641/13127706/da7390b6-d59e-11e5-87b0-fd285f75306a.png)

**Comment by WCapelle** [comment]
To add to this it'd be nice if the recyclers could either be toggled on/off in the editor, and show the on/off effect in the LS window, or have the LS window assume that all converters will be running for the duration.

**Comment by apocriva** [comment]
This would be an excellent feature, as someone still trying to get initial colonies up and running.

**Comment by WCapelle** [comment]
To further my previous comment I did a little digging into the code. Recompiling with the [not is active](https://github.com/BobPalmer/USI-LS/blob/99ba630b84f8a5dcd3702419d0ee3c6b03d98ffb/Source/USILifeSupport/LifeSupportManager.cs#L297) check commented out resulted in the editor window giving me the updated values whenever I attached a science lab to my command pod. I don't know if it needs a scene check or what there, but since that function seems to be used only for the editor check, and since recycler modules can't be toggled in editor, that would be the fix. Or a toggle on the editor USI window.

**Comment by LouisB3** [comment]
In the meantime I have created an index of life support values for USI parts in the [wiki](https://github.com/BobPalmer/USI-LS/wiki). Ideally we would have both the in-game and out-of-game reference. The wiki must be maintained by hand and will necessarily be incomplete depending on the which mods and patches folks have installed, while the VAB info is generated dynamically and would always be correct (barring bugs, etc.)

**Comment by LouisB3** [comment]
The new life support status window shows all of this info in a format that is arguably more useful, so I'll close this as complete.
